FROM golang:1.26.1 AS build-stage
WORKDIR /app
COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /notifier ./cmd/main.go

FROM gcr.io/distroless/base-debian11 AS build-release-stage
WORKDIR /
COPY --from=build-stage /notifier /notifier
USER nonroot:nonroot
ENTRYPOINT ["/notifier"]